[tool.poetry]
name = "termux-monitor"
version = "0.1.0"
description = ""
authors = ["Ashish Kandu <ashishkandu43@gmail.com>"]
readme = "README.md"
packages = [{include = "termux_monitor", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
